#################################################################
#                      Biostatistical Methods I                 #
#          Contingency Tables: Tests for Categorical Data       #
#                          Author: Cody Chiuzan                 #
#################################################################

rm(list=ls())

###############################################################
#      Fisher's Exact test for small cell counts (Eij < 5)    #
###############################################################

# Tea-time experiment
# One-tailed test: calculations were also made in the lecture notes

tea_exp<-matrix(c(3,1,1,3),nrow=2)

fisher.test(tea_exp, alternative="greater")
# P-val=0.2429, fail to conclude discriminating ability

# Two-sided Fisher test
fisher.test(tea_exp)
# P-val=0.4857
# CI is for the odds ratio, not difference in proportions

# What if we used a chi-square instead? Not ideal as the exp freq are <5
chisq.test(tea_exp)
# P-val=0.4795

# Notice that the two-sided p-value from Fisher is greater than the one generated by chi-square
# This supports the conclusion that Fisher Exat Test is more conservative (harder to reject)



practice_data<-matrix(c(1,8,9,3), nrow=2,
                      dimnames=list(c("diet","non-diet"),c("men","women")))

chisq.test(practice_data)
# Pearson's Chi-squared test with Yates' continuity correction for 2X2 table
# X-squared = 6.0494, df = 1, p-value = 0.01391
# Warning message:
# In chisq.test(practice_data) : Chi-squared approximation may be incorrect

fisher.test(practice_data)
# Fisher's Exact Test for Count Data
# p-value = 0.007519  # Notice the difference in p-values b/w chi-squared and Fisher



###############################################################
#      McNemar Test for binomial matched-pair data            #
#               Normal approximation                          #
###############################################################

# Two procedures are tested on the same 75 subjects 
# in order to identify the absence/presence of the disease

procedure_data<-matrix(c(41,8,14,12), nrow=2, byrow=T,
                       dimnames=list(c("positive","negative"),c("positive","negative")))

mcnemar.test(procedure_data)

# McNemar's Chi-squared test with continuity correction
# McNemar's Chi-squared = 1.1364, df = 1, p-value = 0.2864

# What if you performed a chi-squared test instead?
chisq.test(procedure_data)

# X-squared = 6.278, df = 1, p-value = 0.01222
# Notice that the conclusions would be totally different.